# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.7.3

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-and-test
        name: Build and test
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - python manage.py test

    - step: &scan-sonarcloud
        name: scan on SonarCloud
        caches:
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-scan:1.0.1
            variables:
              SONAR_TOKEN: "d85406b28e59c5eb82d4aa252cfd3e971dae3fb7"

    - step: &quality-gate-check
        name: Quality gate Check
        caches:
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.3
            variables:
              SONAR_TOKEN: "d85406b28e59c5eb82d4aa252cfd3e971dae3fb7"

pipelines:
  default:
    - step: *build-and-test

  pull-requests:
    "**":
      - step: *scan-sonarcloud
      - step: *quality-gate-check
